CREATE TABLE EMPLOYEES(
ID NUMBER(*,0) PRIMARY KEY,
DATE_OF_JOINING DATE NOT NULL,
FULL_NAME VARCHAR2(255 BYTE) NOT NULL,
MANAGER_ID NUMBER(*,0) CONSTRAINT FK_MANAGER REFERENCES EMPLOYEES(ID)
);

CREATE TABLE PROJECTS(
ID NUMBER(*,0) PRIMARY KEY,
CODE VARCHAR2(255 BYTE) NOT NULL,
BUDGET NUMBER(10,2) NOT NULL,
DATE_OF_BEGINNING DATE,
DATE_OF_ENDING DATE,
MANAGER_ID NUMBER(*,0) CONSTRAINT FK_MANAGER_PROJEC REFERENCES EMPLOYEES(ID)
);

CREATE TABLE SALARIES(
ID NUMBER(*,0) PRIMARY KEY,
SALARY NUMBER(10,2) NOT NULL CONSTRAINT CHK_GREATER CHECK (SALARY>1000),
EMPLOYEE_ID NUMBER(*,0) NOT NULL CONSTRAINT FK_SALARY_EMPLOYEE REFERENCES EMPLOYEES(ID),
PROJECT_ID NUMBER(*,0) CONSTRAINT FK_SALARY_PROJECT REFERENCES PROJECTS(ID) 
);

SELECT COUNT(*) FROM SALARIES SA
JOIN EMPLOYEES EM ON EM.ID=SA.EMPLOYEE_ID
JOIN PROJECTS PR ON PR.ID=SA.PROJECT_ID
WHERE PR.CODE='48205501099';

SELECT EM.FULL_NAME FROM SALARIES SA
JOIN EMPLOYEES EM ON EM.ID=SA.EMPLOYEE_ID
WHERE SA.SALARY>=2500 AND SA.SALARY<=3000;